[package]
name = "deri"
version = "1.0.0"
authors = []

[addresses]
deri = "0xcafe"
admin = "0xcafe1"
protocol_fee_manager = "0xcafe1"
liq_claim = "0xcafe1"
b0_token = "0xcafe2"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }

[dev-dependencies]
